# Generated by Django 5.2.15 on 2026-06-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_type', models.CharField(choices=[('eggs', 'Egg Production'), ('meat', 'Meat Production'), ('profit', 'Profit Forecast'), ('expenses', 'Expense Forecast')], max_length=50)),
                ('forecast_date', models.DateField()),
                ('predicted_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('actual_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('accuracy_percentage', models.FloatField(default=0)),
                ('method', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-forecast_date'],
            },
        ),
    ]
