# Generated by Django 5.2.15 on 2026-06-29 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreedInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(max_length=50)),
                ('egg_production_per_year', models.IntegerField(blank=True, null=True)),
                ('growth_period_days', models.IntegerField(blank=True, null=True)),
                ('average_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('feed_consumption_daily_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('lifespan_years', models.IntegerField(blank=True, null=True)),
                ('characteristics', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Breed Information',
            },
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_status', models.CharField(choices=[('healthy', 'Healthy'), ('sick', 'Sick'), ('treated', 'Treated'), ('recovered', 'Recovered')], default='healthy', max_length=50)),
                ('disease_name', models.CharField(blank=True, max_length=100)),
                ('treatment', models.TextField(blank=True)),
                ('medication', models.CharField(blank=True, max_length=255)),
                ('vaccination_name', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='flocks.flock')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MortalityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('reason', models.CharField(choices=[('disease', 'Disease'), ('predation', 'Predation'), ('stress', 'Stress'), ('accident', 'Accident'), ('age', 'Age'), ('unknown', 'Unknown')], default='unknown', max_length=50)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mortality_records', to='flocks.flock')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ProductionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('eggs', 'Eggs'), ('meat_ready', 'Meat Ready'), ('feathers', 'Feathers'), ('other', 'Other')], max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(default='units', max_length=50)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_records', to='flocks.flock')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('flock', 'product_type', 'date')},
            },
        ),
    ]
