# Generated by Django 4.2.13 on 2026-07-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mortalityrecord',
            name='flock_quantity_applied',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
