# Generated by Django 4.2.13 on 2026-07-04 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0002_mortalityrecord_flock_quantity_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='mortalityrecord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mortality_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productionrecord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
