# Generated by Django 4.2.13 on 2026-07-04 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_backfill_transaction_records'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoosterAgeEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(blank=True, upload_to='rooster_age_estimates/%Y/%m/')),
                ('photo_name', models.CharField(blank=True, max_length=255)),
                ('spur_visibility', models.CharField(choices=[('clear', 'Spurs clearly visible'), ('partial', 'Partially visible'), ('hidden', 'Hidden or not visible')], max_length=20)),
                ('spur_length', models.CharField(choices=[('none', 'None visible'), ('buds', 'Small buds'), ('short', 'Short'), ('medium', 'Medium'), ('long', 'Long')], max_length=20)),
                ('spur_thickness', models.CharField(choices=[('thin', 'Thin'), ('moderate', 'Moderate'), ('thick', 'Thick')], max_length=20)),
                ('spur_point_shape', models.CharField(choices=[('rounded', 'Rounded or blunt'), ('pointed', 'Sharp pointed'), ('worn', 'Worn or irregular')], max_length=20)),
                ('spur_curvature', models.CharField(choices=[('straight', 'Straight'), ('slight', 'Slightly curved'), ('curved', 'Strongly curved')], max_length=20)),
                ('secondary_clues', models.TextField(blank=True)),
                ('estimated_age_range', models.CharField(max_length=120)),
                ('spur_observations', models.TextField()),
                ('reasoning', models.TextField()),
                ('confidence', models.CharField(max_length=40)),
                ('limitations', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooster_age_estimates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
