# Generated by Django 4.2.13 on 2026-07-04 10:52

from django.db import migrations


def backfill_record_owners(apps, schema_editor):
    UserProfile = apps.get_model('accounts', 'UserProfile')
    Flock = apps.get_model('flocks', 'Flock')
    Inventory = apps.get_model('inventory', 'Inventory')
    Revenue = apps.get_model('revenue', 'Revenue')
    Expense = apps.get_model('expenses', 'Expense')
    ProductionRecord = apps.get_model('production', 'ProductionRecord')
    MortalityRecord = apps.get_model('production', 'MortalityRecord')

    legacy_user = (
        UserProfile.objects
        .filter(is_staff=False, is_superuser=False)
        .order_by('id')
        .first()
    )
    if legacy_user is None:
        legacy_user = UserProfile.objects.order_by('id').first()
    if legacy_user is None:
        return

    Flock.objects.filter(user__isnull=True).update(user=legacy_user)
    Inventory.objects.filter(user__isnull=True).update(user=legacy_user)
    Expense.objects.filter(user__isnull=True).update(user=legacy_user)

    for revenue in Revenue.objects.filter(user__isnull=True).select_related('flock'):
        revenue.user_id = revenue.flock.user_id if revenue.flock_id and revenue.flock.user_id else legacy_user.id
        revenue.save(update_fields=['user'])

    for record in ProductionRecord.objects.filter(user__isnull=True).select_related('flock'):
        record.user_id = record.flock.user_id if record.flock_id and record.flock.user_id else legacy_user.id
        record.save(update_fields=['user'])

    for record in MortalityRecord.objects.filter(user__isnull=True).select_related('flock'):
        record.user_id = record.flock.user_id if record.flock_id and record.flock.user_id else legacy_user.id
        record.save(update_fields=['user'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0006_roosterageestimate'),
        ('expenses', '0002_expense_user'),
        ('flocks', '0003_flock_user_alter_flock_flock_id_and_more'),
        ('inventory', '0002_inventory_user'),
        ('production', '0003_mortalityrecord_user_productionrecord_user'),
        ('revenue', '0002_revenue_user'),
    ]

    operations = [
        migrations.RunPython(backfill_record_owners, migrations.RunPython.noop),
    ]
