# Generated by Django 5.2.15 on 2026-06-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flock_id', models.CharField(max_length=100, unique=True)),
                ('breed', models.CharField(choices=[('layers', 'Layers'), ('broilers', 'Broilers'), ('ducks', 'Ducks'), ('turkeys', 'Turkeys'), ('other', 'Other')], max_length=50)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('sold', 'Sold'), ('deceased', 'Deceased'), ('retired', 'Retired')], default='active', max_length=20)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('expected_production_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
    ]
