# Generated by Django 4.2.13 on 2026-07-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flock',
            name='breed',
            field=models.CharField(choices=[('layers', 'Layers'), ('broilers', 'Broilers'), ('other', 'Other')], max_length=50),
        ),
    ]
