# Generated by Django 4.2.13 on 2026-07-04 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flocks', '0002_alter_flock_breed'),
    ]

    operations = [
        migrations.AddField(
            model_name='flock',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flocks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='flock',
            name='flock_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='flock',
            constraint=models.UniqueConstraint(fields=('user', 'flock_id'), name='unique_flock_id_per_user'),
        ),
    ]
